<a href="https://colab.research.google.com/github/viswatejareddygudddeti/ml-project/blob/main/Task3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas numpy scikit-learn matplotlib seaborn

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving movie recomendation.csv to movie recomendation.csv

In [ ]:
df = pd.read_csv("movie recomendation.csv")

df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020.0,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021.0,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021.0,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021.0,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [ ]:
df = df[['title','listed_in','cast','director','description']]

df = df.fillna('')

df['content'] = df['listed_in'] + " " + df['cast'] + " " + df['director'] + " " + df['description']

df.head()

,title,listed_in,cast,director,description,content
0,Dick Johnson Is Dead,Documentaries,,Kirsten Johnson,"As her father nears the end of his life, filmm...",Documentaries Kirsten Johnson As her father n...
1,Blood & Water,"International TV Shows, TV Dramas, TV Mysteries","Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",,"After crossing paths at a party, a Cape Town t...","International TV Shows, TV Dramas, TV Mysterie..."
2,Ganglands,"Crime TV Shows, International TV Shows, TV Act...","Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Julien Leclercq,To protect his family from a powerful drug lor...,"Crime TV Shows, International TV Shows, TV Act..."
3,Jailbirds New Orleans,"Docuseries, Reality TV",,,"Feuds, flirtations and toilet talk go down amo...","Docuseries, Reality TV Feuds, flirtations an..."
4,Kota Factory,"International TV Shows, Romantic TV Shows, TV ...","Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",,In a city of coaching centers known to train I...,"International TV Shows, Romantic TV Shows, TV ..."

In [ ]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub('[^a-zA-Z ]','', text)
    return text

df['content'] = df['content'].apply(clean_text)

In [ ]:
tfidf = TfidfVectorizer(stop_words='english')

tfidf_matrix = tfidf.fit_transform(df['content'])

tfidf_matrix.shape

(8807, 49821)

In [ ]:
cosine_sim = cosine_similarity(tfidf_matrix, tfidf_matrix)

cosine_sim

array([[1.        , 0.        , 0.        , ..., 0.        , 0.01007725,
        0.        ],
       [0.        , 1.        , 0.02281725, ..., 0.        , 0.        ,
        0.00307711],
       [0.        , 0.02281725, 1.        , ..., 0.        , 0.0050369 ,
        0.00658337],
       ...,
       [0.        , 0.        , 0.        , ..., 1.        , 0.04555003,
        0.00191173],
       [0.01007725, 0.        , 0.0050369 , ..., 0.04555003, 1.        ,
        0.00745303],
       [0.        , 0.00307711, 0.00658337, ..., 0.00191173, 0.00745303,
        1.        ]])

In [ ]:
indices = pd.Series(df.index, index=df['title']).drop_duplicates()

def recommend_movie(title, cosine_sim=cosine_sim):

    idx = indices[title]

    sim_scores = list(enumerate(cosine_sim[idx]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:6]

    movie_indices = [i[0] for i in sim_scores]

    return df['title'].iloc[movie_indices]

In [ ]:
recommend_movie("Blood & Water")

1514        Diamond City
1593    Kings of Jo'Burg
4475            Shirkers
4271          Lion Pride
108            Dive Club
Name: title, dtype: object

In [ ]:
X = tfidf_matrix
y = df['listed_in']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = RandomForestClassifier()

model.fit(X_train, y_train)

RandomForestClassifier()

In [ ]:
params = {
    'n_estimators':[50,100],
    'max_depth':[10,20]
}

grid = GridSearchCV(
    RandomForestClassifier(),
    params,
    cv=3
)

grid.fit(X_train, y_train)

best_model = grid.best_estimator_

best_model

/usr/local/lib/python3.12/dist-packages/sklearn/model_selection/_split.py:805: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=3.
  warnings.warn(

RandomForestClassifier(max_depth=20, n_estimators=50)

In [ ]:
y_pred = best_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy: 0.21679909194097616
                                                                                 precision    recall  f1-score   support

                                                                                      0.10      1.00      0.18       134
                                                             Action & Adventure       0.00      0.00      0.00        27
                             Action & Adventure, Anime Features, Classic Movies       0.00      0.00      0.00         1
                       Action & Adventure, Anime Features, International Movies       0.83      0.62      0.71         8
                           Action & Adventure, Anime Features, Sci-Fi & Fantasy       0.00      0.00      0.00         1
                   Action & Adventure, Children & Family Movies, Classic Movies       0.00      0.00      0.00         1
                         Action & Adventure, Children & Family Movies, Comedies       0.00      0.00      0.00         1
                 Action & Adventure, Children & Family Movies, Sci-Fi & Fantasy       1.00      1.00      1.00         1
                                             Action & Adventure, Classic Movies       0.00      0.00      0.00         1
                                   Action & Adventure, Classic Movies, Comedies       0.00      0.00      0.00         2
                                     Action & Adventure, Classic Movies, Dramas       0.00      0.00      0.00         4
                                                   Action & Adventure, Comedies       0.00      0.00      0.00        12
                                      Action & Adventure, Comedies, Cult Movies       0.00      0.00      0.00         1
                                           Action & Adventure, Comedies, Dramas       0.00      0.00      0.00         3
                             Action & Adventure, Comedies, International Movies       0.00      0.00      0.00        15
                                 Action & Adventure, Comedies, Music & Musicals       0.00      0.00      0.00         1
                                 Action & Adventure, Comedies, Sci-Fi & Fantasy       0.00      0.00      0.00         2
                                                     Action & Adventure, Dramas       0.00      0.00      0.00         4
                                 Action & Adventure, Dramas, Independent Movies       0.00      0.00      0.00         2
                               Action & Adventure, Dramas, International Movies       1.00      0.08      0.15        24
                                   Action & Adventure, Dramas, Sci-Fi & Fantasy       0.00      0.00      0.00         1
                                      Action & Adventure, Dramas, Sports Movies       0.00      0.00      0.00         1
                          Action & Adventure, Horror Movies, Independent Movies       0.00      0.00      0.00         1
                        Action & Adventure, Horror Movies, International Movies       0.00      0.00      0.00         2
                            Action & Adventure, Horror Movies, Sci-Fi & Fantasy       0.00      0.00      0.00         2
                       Action & Adventure, Independent Movies, Sci-Fi & Fantasy       0.00      0.00      0.00         1
                                       Action & Adventure, International Movies       1.00      0.04      0.08        24
                     Action & Adventure, International Movies, Music & Musicals       0.00      0.00      0.00         1
                      Action & Adventure, International Movies, Romantic Movies       0.00      0.00      0.00         1
                     Action & Adventure, International Movies, Sci-Fi & Fantasy       0.00      0.00      0.00         3
                        Action & Adventure, International Movies, Sports Movies       0.00      0.00      0.00         1
                            Action & Adventure, International Movies, Thrillers       0.00      0.00      0.00         1
                                           Action & Adventure, Sci-Fi & Fantasy       0.00      0.00      0.00        12
                            Action & Adventure, Sci-Fi & Fantasy, Sports Movies       0.00      0.00      0.00         1
                                                  Action & Adventure, Thrillers       0.00      0.00      0.00         2
                 Anime Features, Children & Family Movies, International Movies       0.00      0.00      0.00         1
                                           Anime Features, International Movies       0.00      0.00      0.00         1
                          Anime Features, International Movies, Romantic Movies       0.00      0.00      0.00         1
                                                                   Anime Series       0.00      0.00      0.00         3
                                                   Anime Series, Crime TV Shows       0.00      0.00      0.00         2
                           Anime Series, Crime TV Shows, International TV Shows       0.00      0.00      0.00         2
                                        Anime Series, Crime TV Shows, TV Horror       0.00      0.00      0.00         1
                                           Anime Series, International TV Shows       0.72      0.68      0.70        19
                        Anime Series, International TV Shows, Romantic TV Shows       0.00      0.00      0.00         2
                Anime Series, International TV Shows, Spanish-Language TV Shows       0.00      0.00      0.00         1
                             Anime Series, International TV Shows, TV Thrillers       0.00      0.00      0.00         1
                            Anime Series, International TV Shows, Teen TV Shows       0.00      0.00      0.00         1
                                                         Anime Series, Kids' TV       0.00      0.00      0.00         3
                                                    Anime Series, Teen TV Shows       0.00      0.00      0.00         1
                    British TV Shows, Classic & Cult TV, International TV Shows       0.00      0.00      0.00         1
                                   British TV Shows, Crime TV Shows, Docuseries       0.00      0.00      0.00         5
                       British TV Shows, Crime TV Shows, International TV Shows       0.00      0.00      0.00         5
                                    British TV Shows, Crime TV Shows, TV Dramas       0.00      0.00      0.00         1
                                                   British TV Shows, Docuseries       0.00      0.00      0.00         1
                           British TV Shows, Docuseries, International TV Shows       0.00      0.00      0.00         6
                              British TV Shows, Docuseries, Science & Nature TV       0.83      0.83      0.83         6
                           British TV Shows, International TV Shows, Reality TV       0.00      0.00      0.00         3
                    British TV Shows, International TV Shows, Romantic TV Shows       0.00      0.00      0.00         2
                British TV Shows, International TV Shows, TV Action & Adventure       0.00      0.00      0.00         1
                          British TV Shows, International TV Shows, TV Comedies       0.00      0.00      0.00         4
                            British TV Shows, International TV Shows, TV Dramas       0.00      0.00      0.00         4
                                                     British TV Shows, Kids' TV       0.00      0.00      0.00         6
                                                   British TV Shows, Reality TV       0.00      0.00      0.00         2
                                                  British TV Shows, TV Comedies       0.00      0.00      0.00         3
                                                       Children & Family Movies       0.66      0.58      0.62        43
                             Children & Family Movies, Classic Movies, Comedies       0.00      0.00      0.00         1
                                             Children & Family Movies, Comedies       0.61      0.78      0.68        36
                       Children & Family Movies, Comedies, International Movies       0.00      0.00      0.00         1
                           Children & Family Movies, Comedies, Music & Musicals       0.00      0.00      0.00         3
                           Children & Family Movies, Comedies, Sci-Fi & Fantasy       0.00      0.00      0.00         3
                                        Children & Family Movies, Documentaries       0.00      0.00      0.00         4
                                               Children & Family Movies, Dramas       0.00      0.00      0.00         4
                         Children & Family Movies, Dramas, International Movies       0.00      0.00      0.00         2
                              Children & Family Movies, Dramas, Romantic Movies       0.00      0.00      0.00         3
                                Children & Family Movies, Dramas, Sports Movies       0.00      0.00      0.00         2
               Children & Family Movies, Faith & Spirituality, Music & Musicals       0.00      0.00      0.00         1
                                   Children & Family Movies, Independent Movies       0.00      0.00      0.00         1
                                     Children & Family Movies, Music & Musicals       0.00      0.00      0.00         5
                                     Children & Family Movies, Sci-Fi & Fantasy       0.00      0.00      0.00         1
                                        Children & Family Movies, Sports Movies       0.00      0.00      0.00         1
                                   Classic & Cult TV, Crime TV Shows, TV Dramas       0.00      0.00      0.00         1
                  Classic & Cult TV, TV Action & Adventure, TV Sci-Fi & Fantasy       0.00      0.00      0.00         1
                                         Classic & Cult TV, TV Sci-Fi & Fantasy       0.00      0.00      0.00         1
                                          Classic Movies, Comedies, Cult Movies       0.00      0.00      0.00         1
                                 Classic Movies, Comedies, International Movies       0.00      0.00      0.00         1
                                      Classic Movies, Comedies, Romantic Movies       0.00      0.00      0.00         1
                                     Classic Movies, Cult Movies, Horror Movies       0.00      0.00      0.00         1
                                                  Classic Movies, Documentaries       0.00      0.00      0.00         2
                                                         Classic Movies, Dramas       0.00      0.00      0.00         2
                                     Classic Movies, Dramas, Independent Movies       0.00      0.00      0.00         3
                                   Classic Movies, Dramas, International Movies       0.00      0.00      0.00         6
                                       Classic Movies, Dramas, Music & Musicals       0.00      0.00      0.00         1
                                        Classic Movies, Dramas, Romantic Movies       0.00      0.00      0.00         1
                                                                       Comedies       0.00      0.00      0.00        26
                                                          Comedies, Cult Movies       0.00      0.00      0.00         2
                                                  Comedies, Cult Movies, Dramas       0.00      0.00      0.00         1
                                           Comedies, Cult Movies, Horror Movies       0.00      0.00      0.00         1
                                    Comedies, Cult Movies, International Movies       0.00      0.00      0.00         1
                                            Comedies, Cult Movies, LGBTQ Movies       0.00      0.00      0.00         1
                                                        Comedies, Documentaries       0.00      0.00      0.00         1
                                  Comedies, Documentaries, International Movies       0.00      0.00      0.00         1
                                                               Comedies, Dramas       0.00      0.00      0.00         6
                                           Comedies, Dramas, Independent Movies       0.00      0.00      0.00        15
                                         Comedies, Dramas, International Movies       0.67      0.09      0.15        46
                                                 Comedies, Dramas, LGBTQ Movies       0.00      0.00      0.00         2
                                             Comedies, Dramas, Music & Musicals       0.00      0.00      0.00         1
                                              Comedies, Dramas, Romantic Movies       0.00      0.00      0.00         2
                                                Comedies, Dramas, Sports Movies       0.00      0.00      0.00         1
                           Comedies, Faith & Spirituality, International Movies       0.00      0.00      0.00         1
                                Comedies, Faith & Spirituality, Romantic Movies       0.00      0.00      0.00         1
                                                        Comedies, Horror Movies       0.00      0.00      0.00         2
                                    Comedies, Horror Movies, Independent Movies       0.00      0.00      0.00         2
                                  Comedies, Horror Movies, International Movies       0.00      0.00      0.00         7
                                                   Comedies, Independent Movies       0.00      0.00      0.00         5
                             Comedies, Independent Movies, International Movies       0.00      0.00      0.00         7
                                     Comedies, Independent Movies, LGBTQ Movies       0.00      0.00      0.00         1
                                        Comedies, Independent Movies, Thrillers       0.00      0.00      0.00         1
                                                 Comedies, International Movies       0.00      0.00      0.00        26
                               Comedies, International Movies, Music & Musicals       0.00      0.00      0.00         9
                                Comedies, International Movies, Romantic Movies       0.75      0.12      0.21        25
                                  Comedies, International Movies, Sports Movies       0.00      0.00      0.00         2
                                      Comedies, International Movies, Thrillers       0.00      0.00      0.00         1
                                                     Comedies, Music & Musicals       0.00      0.00      0.00         1
                                    Comedies, Music & Musicals, Romantic Movies       0.00      0.00      0.00         1
                                                      Comedies, Romantic Movies       0.00      0.00      0.00        16
                                                     Crime TV Shows, Docuseries       0.00      0.00      0.00         9
                             Crime TV Shows, Docuseries, International TV Shows       1.00      0.25      0.40         4
                        Crime TV Shows, International TV Shows, Korean TV Shows       0.00      0.00      0.00         3
                      Crime TV Shows, International TV Shows, Romantic TV Shows       0.00      0.00      0.00         1
              Crime TV Shows, International TV Shows, Spanish-Language TV Shows       1.00      0.36      0.53        14
                  Crime TV Shows, International TV Shows, TV Action & Adventure       0.00      0.00      0.00         3
                            Crime TV Shows, International TV Shows, TV Comedies       0.00      0.00      0.00         4
                              Crime TV Shows, International TV Shows, TV Dramas       0.50      0.04      0.08        24
                   Crime TV Shows, Romantic TV Shows, Spanish-Language TV Shows       0.00      0.00      0.00         1
                                   Crime TV Shows, Romantic TV Shows, TV Dramas       0.00      0.00      0.00         1
                           Crime TV Shows, Spanish-Language TV Shows, TV Dramas       0.00      0.00      0.00         1
                            Crime TV Shows, TV Action & Adventure, TV Thrillers       0.00      0.00      0.00         1
                                         Crime TV Shows, TV Comedies, TV Dramas       0.00      0.00      0.00         3
                                                      Crime TV Shows, TV Dramas       0.00      0.00      0.00         4
                                        Crime TV Shows, TV Dramas, TV Mysteries       0.00      0.00      0.00         4
                                        Crime TV Shows, TV Horror, TV Mysteries       0.00      0.00      0.00         1
                                      Cult Movies, Dramas, International Movies       0.00      0.00      0.00         1
                                          Cult Movies, Dramas, Music & Musicals       0.00      0.00      0.00         1
                                                 Cult Movies, Dramas, Thrillers       0.00      0.00      0.00         1
                                                     Cult Movies, Horror Movies       0.00      0.00      0.00         2
                                 Cult Movies, Horror Movies, Independent Movies       0.00      0.00      0.00         1
                                                                  Documentaries       0.33      0.50      0.40        62
                                            Documentaries, Faith & Spirituality       0.00      0.00      0.00         1
                                            Documentaries, International Movies       1.00      0.06      0.11        34
                              Documentaries, International Movies, LGBTQ Movies       0.00      0.00      0.00         2
                          Documentaries, International Movies, Music & Musicals       0.00      0.00      0.00         9
                             Documentaries, International Movies, Sports Movies       0.00      0.00      0.00         8
                                                    Documentaries, LGBTQ Movies       0.00      0.00      0.00         5
                                                Documentaries, Music & Musicals       0.00      0.00      0.00        14
                                                   Documentaries, Sports Movies       0.75      0.55      0.63        11
                                                                     Docuseries       0.00      0.00      0.00        16
                                             Docuseries, International TV Shows       0.00      0.00      0.00         5
                                 Docuseries, International TV Shows, Reality TV       0.00      0.00      0.00         3
                        Docuseries, International TV Shows, Science & Nature TV       0.00      0.00      0.00         2
                  Docuseries, International TV Shows, Spanish-Language TV Shows       0.00      0.00      0.00         3
                                                         Docuseries, Reality TV       0.00      0.00      0.00         4
                                    Docuseries, Reality TV, Science & Nature TV       0.00      0.00      0.00         1
                                                Docuseries, Science & Nature TV       0.00      0.00      0.00         9
                                          Docuseries, Spanish-Language TV Shows       0.00      0.00      0.00         1

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [ ]:
import pickle

pickle.dump(best_model, open("movie_model.pkl","wb"))
pickle.dump(tfidf, open("tfidf.pkl","wb"))

In [18]:
!streamlit run app.py &>/dev/null&

In [19]:
!pip install streamlit pyngrok

Requirement already satisfied: streamlit in /usr/local/lib/python3.12/dist-packages (1.55.0)
Collecting pyngrok
  Downloading pyngrok-7.5.1-py3-none-any.whl.metadata (8.2 kB)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<8,>=5.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.1)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.46)
Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)
Requirement already satisfied: packaging>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (26.0)
Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)
Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.9.1)
Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.6)
Requirement already satisfied: pyarrow>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)
Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (9.1.4)
Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)
Requirement already satisfied: PyYAML>=5.1 in /usr/local/lib/python3.12/dist-packages (from pyngrok) (6.0.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.26.0)
Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.17.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Downloading pyngrok-7.5.1-py3-none-any.whl (24 kB)
Installing collected packages: pyngrok
Successfully installed pyngrok-7.5.1

In [20]:
%%writefile app.py

import streamlit as st

st.title("🎬 Movie Recommendation System")

movie = st.text_input("Enter movie name")

if st.button("Recommend"):
    st.write("Recommended Movies:")
    st.write("Movie 1")
    st.write("Movie 2")
    st.write("Movie 3")

Writing app.py

In [21]:
!streamlit run app.py &>/dev/null&

In [23]:
import streamlit as st
import pandas as pd
import pickle

model = pickle.load(open("movie_model.pkl","rb"))
tfidf = pickle.load(open("tfidf.pkl","rb"))

st.title("Movie Recommendation System")

movie_input = st.text_input("Enter movie description")

if st.button("Predict Genre"):

    vec = tfidf.transform([movie_input])

    prediction = model.predict(vec)

    st.write("Predicted Genre:", prediction[0])

2026-03-08 16:36:11.052 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-08 16:36:11.057 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-08 16:36:11.060 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-08 16:36:11.073 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-08 16:36:11.080 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-08 16:36:11.086 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-08 16:36:11.093 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-08 16:36:11.099 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-08 16:36:11.113 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-08 16:36:11.119 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-08 16:36:11.126 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-08 16:36:11.132 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-08 16:36:11.138 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-08 16:36:11.142 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-08 16:36:11.144 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-08 16:36:11.149 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [ ]:
!streamlit run app.py

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8502
  Network URL: http://172.28.0.12:8502
  External URL: http://34.87.64.204:8502